### ISSUE TITLE
Optimizing asarray

### ISSUE THREAD

**Issue by kchanqvq** [digikar99/dense-arrays#7]
It turns out `asarray` quite often becomes performance bottleneck of `dense-numericals` (it's impressive how fast the rest of the library is!), so I'm putting it on my TODO list to optimize.

Some questions:
1. `asarray` does quite a bit of keyword argument processing (and depending on whether argument is passed explicitly), what is the recommended way to upgrade it to a polymorph? In my prototype I find it easier to have a `(define-polymorphic-function asarray-impl (in-array out-array))` and keep `asarray` as an ordinary function which calls `asarray-impl`. Is this idiomatic enough?
2. Once I specialize on `(out-array <out-type>)`, is it possible to pass `<out-type>` to `do-arrays`?
3. Ideally, we can use bmas to accelerate `asarray` even more. Do we want that in `dense-arrays`? That implies adding bmas as a dependency.

**Comment by digikar99** [comment]
I'm not expecting asarray to be used in high performance code. For that, I think zeros/ones/empty and friends should be used along with aref or do-array. So, I'm curious on the use case.

Regardless, it'd be interesting to figure out a good way to make asarray faster.

1. One possibility to implement asarray as a polymorph is as given here: https://github.com/digikar99/numericals/blob/master/src/utils/asarray.lisp but I suspect it suffers from similar performance issues. The current interface and implementation of asarray is definitely unsatisfactory and requires more thought.
2. Assuming the asarray-impl polymorph gets inlined, do-arrays should pick up the array element type appropriately. The do-arrays macro looks into the environment using cltl2: https://github.com/digikar99/dense-arrays/blob/9d1e1fc480bca9043fc80c17bbf891962db7f501/src/do-arrays.lisp#L211-217
3. I'm opposed to including bmas as a dependency for dense-arrays or its plus-lite counterparts. However, we can provide another asarray within dense-numericals that uses bmas. This will shadow dense-arrays:asarray.

Another direction to look into is also whether you want a fast asarray with inlining or even without inlining. For the latter, peltadot:specializing (based upon specializing-function:specializing) should be helpful.

**Comment by kchanqvq** [comment]
> I'm not expecting asarray to be used in high performance code.

They are called by other primitives to perform type coercion, for example `+ - * /`. It's a bit surprising for me to find out these code spent lots of time running asarray as well!

**Comment by digikar99** [comment]
> > I'm not expecting asarray to be used in high performance code.
> 
> They are called by other primitives to perform type coercion, for example `+ - * /`. It's a bit surprising for me to find out these code spent lots of time running asarray as well!

I see what you mean!

https://github.com/digikar99/numericals/blob/588f885ce6a20d91c6b815d768eb3edf7bcbe274/src/basic-math/n-arg-fn.lisp#L36

That's a good point. I have probably mentioned it as the first TODO. Rather than trivial-coerce:coerce or now peltadot:coerce, one could use a combination of `empty` with `(copy from :out to)`. 

An even better solution can avoid array allocation altogether. This will involve (i) extending BMAS to add operations for nonuniform element types (ii) extending translation tables with double hashing (iii) introducing two-arg-fn functions for nonuniform element types. But this is much more work for a questionable benefit. If performance matters so much, I'm guessing people will stick to a single element type right from the start to avoid conversions altogether.
